name: skycheckers
base: core18
version: '1.2.1'
summary: Blast enemies off a stage
description: |
  Blast off your enemies in a 1-4 multiplayer action packed battle and be the last one standing!

grade: stable
confinement: strict

architectures:
  - amd64

apps:
  skycheckers:
    command: bin/skycheckers --base $SNAP/usr/share/skycheckers/
    desktop: usr/share/applications/com.zgcoder.skycheckers.desktop
    environment:
      # https://forum.snapcraft.io/t/opengl-error-mesa-loader-fails/15197
      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/mesa:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/mesa-gl:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/xorg
      LIBGL_DRIVERS_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri
    plugs:
      - opengl
      - audio-playback
      - network
      - network-bind
      - joystick
      - screen-inhibit-control
      - wayland
      - x11

parts:
  skycheckers:
    after: [sdl2, desktop-glib-only]
    source: https://github.com/zorgiepoo/Sky-Checkers.git
    source-subdir: linux
    plugin: make
    build-packages:
      - libsdl2-mixer-dev
      - libsdl2-ttf-dev
      - libglew-dev
    stage-packages:
      - libsdl2-mixer-2.0-0
      - libsdl2-ttf-2.0-0
      - libglew2.0
      - libglu1-mesa
    override-pull: |
      snapcraftctl pull
      sed -i 's/Icon=com.zgcoder.skycheckers.icon.png/Icon=\/usr\/share\/icons\/com.zgcoder.skycheckers.icon.png/g' linux/com.zgcoder.skycheckers.desktop
    prime:
      - -usr/share/skycheckers/Data/Textures/sc_icon.bmp
  sdl2:
    source: https://www.libsdl.org/release/SDL2-2.0.12.tar.gz
    plugin: autotools
    build-packages:
      - libx11-dev

  # https://forum.snapcraft.io/t/adding-opengl-gpu-support-to-a-snap/6273
  # https://github.com/ubuntu/snapcraft-desktop-helpers/blob/master/snapcraft.yaml
  desktop-glib-only:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: glib-only
    plugin: make
    build-packages:
      - libglib2.0-dev
    stage-packages:
      - libglib2.0-bin

