name: skycheckers
base: core18
version: '1.2'
summary: Blast enemies off a stage
description: |
  Blast off your enemies in a 1-4 multiplayer action packed battle and be the last one standing!

grade: devel
confinement: devmode

apps:
  skycheckers:
    command: bin/skycheckers --base usr/share/skycheckers/

parts:
  skycheckers:
    after: [sdl2]
    source: https://github.com/zorgiepoo/Sky-Checkers.git
    source-subdir: linux
    plugin: make
    build-packages:
      - libsdl2-mixer-dev
      - libsdl2-ttf-dev
      - libglew-dev
    stage-packages:
      - libsdl2-mixer-2.0-0
      - libsdl2-ttf-2.0-0
      - libglew2.0
  
  sdl2:
    source: https://www.libsdl.org/release/SDL2-2.0.12.tar.gz
    plugin: autotools
    build-packages:
      - libx11-dev


